[package]
name = "aoc-23"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
nom = "7.1.3"

[[bin]]
name = "day01"
path = "src/day-01.rs"

[[bin]]
name = "day02"
path = "src/day-02.rs"
